### ISSUE TITLE
CMake error with pagmo

### ISSUE THREAD

**Issue by ThijsRoumen** [ShnitzelKiller/Reverse-Engineering-Carpentry#1]
Hey there, great project! Would love to build it (but I run into this CMake issue --I wish I had a more interesting issue related to the content instead of the logistics though..)

CMake Error at CMakeLists.txt:29 (INCLUDE):
  INCLUDE could not find load file:

    /usr/local/lib/cmake/pagmo/FindEigen3.cmake

It is correct that this folder does not exist within pagmo. 

pagmo % ls
Findpagmo_IPOPT.cmake		pagmo-config.cmake
PagmoFindBoost.cmake		pagmo_export-release.cmake
pagmo-config-version.cmake	pagmo_export.cmake

Should I build pagmo from source and explicitly set the optional dependency Eigen3? I do have Eigen3 set up via home-brew. Is there a way to just mod the CMakeLists so that it does not attempt to findEigen3 via pagmo but search for the header directly? 

Thanks!

**Comment by ShnitzelKiller** [comment]
Sorry, it was a leftover from a custom build of pagmo that I needed to build with functioning multiprocessing. Should be fixed now.
